# Generated by Django 5.0.4 on 2024-04-27 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
        ('cliente', '0002_alter_cliente_apellido_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulo.articulo', verbose_name='Cliente'),
        ),
    ]
