# Generated by Django 5.0.4 on 2024-04-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
        ('cliente', '0003_remove_pedido_precio_alter_pedido_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='', max_length=200, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(default=0, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulo.articulo', verbose_name='Artículo'),
        ),
    ]
