# Generated by Django 5.0.4 on 2024-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_ciudad_cliente_dni_alter_pedido_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.PositiveIntegerField(unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='DNI'),
        ),
    ]
