# Generated by Django 5.0.4 on 2024-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_dni_alter_pedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
    ]
