# Generated by Django 5.0.4 on 2024-05-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_cliente_fecha_nacimiento_pedido_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
