# Generated by Django 5.0.4 on 2024-05-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Cantidad'),
        ),
    ]
