# Generated by Django 5.0.4 on 2024-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_alter_pedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
