# Generated by Django 5.0.4 on 2024-05-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_articulo_fecha_actualizacion_alter_articulo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio'),
        ),
    ]
