# Generated by Django 5.0.4 on 2024-05-20 00:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('fecha_alta', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Fecha de Alta')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
    ]
